SHELL := /bin/bash
.DEFAULT_GOAL := help

# Local development never pays for ship-only optimisations. These override the
# single [profile.release] in Cargo.toml through the environment, so the output
# path stays target/release/... and nothing downstream needs to know.
DEV_FAST := CARGO_PROFILE_RELEASE_LTO=false CARGO_PROFILE_RELEASE_CODEGEN_UNITS=16

# Speed-oriented native codegen. The single [profile.release] is tuned for the
# wasm module, which is the only binary with a size budget; opt-level="z" would
# make a parse or layout timing meaningless and would ship a needlessly slow
# desktop application. Benchmarks and the packaged desktop build therefore ask
# for speed explicitly. Same profile, same path.
NATIVE_FAST := CARGO_PROFILE_RELEASE_OPT_LEVEL=3 CARGO_PROFILE_RELEASE_LTO=thin \
              CARGO_PROFILE_RELEASE_CODEGEN_UNITS=16

.PHONY: help
help:
	@grep -E '^[a-zA-Z0-9_-]+:.*?## ' $(MAKEFILE_LIST) \
	  | awk 'BEGIN{FS=":.*?## "}{printf "  \033[36m%-18s\033[0m %s\n", $$1, $$2}'

.PHONY: fixtures
fixtures: ## Regenerate fixtures/ from the seeded generator
	node fixtures/gen/gen.mjs

.PHONY: test
test: ## Run all tests (dev profile; fast to build)
	cargo test --workspace

.PHONY: test-release
test-release: ## Run tests with the shipped codegen, so timing gates mean something
	$(DEV_FAST) cargo test --workspace --release

.PHONY: bench
bench: ## Build spikes with speed-oriented codegen and run them
	$(NATIVE_FAST) cargo run --release -p layout-eval

.PHONY: dev-build
dev-build: ## Release build without ship-only optimisations
	$(DEV_FAST) cargo build --release --workspace

.PHONY: ship
ship: ## Full release build with every size optimisation on
	cargo build --release --workspace

.PHONY: app
app: ## Run the desktop application
	$(NATIVE_FAST) cargo run --release -p draft-app -- $(ARGS)

.PHONY: web-build
web-build: ## Build the shipped web bundle into crates/app/dist
	cd crates/app && trunk build --release

.PHONY: web-serve
web-serve: ## Serve the web application with rebuild-on-change
	cd crates/app && trunk serve

.PHONY: payload
payload: web-build ## Report the brotli payload against the budget
	node web/payload.mjs

# The canvas and typing gates. Native numbers are only a lower bound for wasm,
# so this is the measurement that decides, not `make bench`.
.PHONY: web-bench
web-bench: web-build ## Measure frame cost in a real browser
	node web/bench.mjs

.PHONY: coldload
coldload: web-build ## Measure cold load to first paint on a throttled connection
	node web/coldload.mjs

.PHONY: shots
shots: web-build ## Screenshot the shipped web bundle into .scratch/shots
	node web/shot.mjs

# Phase 6's gate. Watches the wire rather than trusting that fragments are
# never transmitted, because that is the whole claim the feature rests on.
.PHONY: share
share: web-build ## Prove a share link round-trips with no network request
	node web/share.mjs

# The pages are generated by running the shipped CLI over the dialect fixtures,
# so the tool has to exist before they can be built.
.PHONY: site
site: web-build ## Build the deployable site (landing pages + app) into web/dist
	$(DEV_FAST) cargo build --release -p draft-cli
	node web/site.mjs

.PHONY: site-serve
site-serve: site ## Serve the built site, so /app/ and the pages can be checked together
	node web/site-serve.mjs

# Phase 7's gate. Link rot and a mis-mounted application are both invisible in
# the generator and obvious in a browser.
.PHONY: site-check
site-check: site ## Visit every page, resolve every link, start the app at /app/
	node web/site-check.mjs

# Phase 8.4's front end, which ships nothing yet: the canvas build in
# crates/app is still the application. No profile overrides here either — this
# bundle has the tighter payload budget of the two.
.PHONY: front-build
front-build: ## Build the DOM/SVG front end into web/front/dist
	bash web/front.sh

.PHONY: front-serve
front-serve: front-build ## Serve the DOM/SVG front end
	node web/serve-front.mjs

# Stage a's gate: the browser measures its own text, the CLI measures with
# epaint, and the two diagrams have to be the same diagram. Stage b adds the
# camera and focus behaviour to the same run, because it is the same browser.
.PHONY: front-check
front-check: front-build ## Compare the front end's geometry against the CLI's SVG
	node web/front-check.mjs

# Stage b's gate. Headful, like web-bench: a headless browser's rasterisation
# says nothing about whether a thousand tables stay interactive.
.PHONY: front-bench
front-bench: front-build ## Measure the front end's frame and typing cost
	node web/front-bench.mjs

# Speed, not size: a downloaded binary has no payload budget, and the shipped
# profile's opt-level="z" exists for the wasm module alone.
.PHONY: desktop
desktop: ## Package the desktop application for this platform into dist/
	$(NATIVE_FAST) cargo build --release -p draft-app -p draft-cli
	bash web/package.sh

# web-build runs with no profile overrides on purpose: the payload number is a
# statement about the shipped profile, so it is the one build that must pay for
# every size optimisation.
.PHONY: budgets
budgets: web-build ## Enforce every shipped budget: payload, parse time, layout time
	$(NATIVE_FAST) cargo test --release -p draft-ddl -p draft-layout -- --nocapture time_budget
	node web/payload.mjs

.PHONY: native-bench
native-bench: ## Measure frame cost natively (fast iteration; not the gate)
	$(NATIVE_FAST) cargo build --release -p draft-app
	./target/release/draft-app --bench canvas 300 600
	./target/release/draft-app --bench canvas 1000 600
	./target/release/draft-app --bench canvas 3000 600
	./target/release/draft-app --bench type 12 600
	./target/release/draft-app --bench type 106 600
	./target/release/draft-app --bench type 396 600

.PHONY: clean-scratch
clean-scratch: ## Drop measurement logs
	rm -rf .scratch
