// Build the static landing pages into web/dist.
//
// These pages are the entire SEO surface (docs/spec.md, "Accessibility and
// SEO"): the application is a canvas with no DOM, so nothing inside it can ever
// be indexed. Everything here is plain HTML with no script and no wasm.
//
// The per-dialect pages are *generated by running the shipped CLI over the
// dialect fixtures*, rather than written by hand. A hand-written claim about
// what the parser supports is a claim that rots the first time the parser
// changes and nobody notices. A generated one cannot: if `draft` stops
// finding the foreign key in the MySQL fixture, this page stops saying it does.
//
// Run: make site   (or: node web/site.mjs)

import { execFileSync } from "node:child_process";
import { cp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = fileURLToPath(new URL(".", import.meta.url));
const ROOT = resolve(HERE, "..");
const DIST = resolve(HERE, "dist");
const CLI = resolve(ROOT, "target/release/draft");
const APP = resolve(ROOT, "crates/app/dist");

// Where the site will be served from. Only used for canonical URLs and the
// sitemap, both of which have to be absolute. There is no domain yet, so the
// default is the local preview origin and a deploy passes SITE_URL.
const SITE = (process.env.SITE_URL ?? "http://localhost").replace(/\/$/, "");

const escape = (s) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

// The counts come out of the parser, so "1 relations" is a real possibility.
const plural = (n, word) => `${n} ${word}${n === 1 ? "" : "s"}`;

/// Run the CLI over a fixture and return both what it parsed and what it drew.
function run(fixture) {
  const file = resolve(ROOT, fixture);
  const facts = JSON.parse(execFileSync(CLI, ["render", file, "--json", "-q"], { encoding: "utf8" }));
  const drawn = execFileSync(CLI, ["render", file, "-q"], { encoding: "utf8" });
  const columns = facts.tables.reduce((n, t) => n + t.columns.length, 0);
  return {
    tables: facts.tables,
    relations: facts.relations,
    columns,
    // Let CSS drive the size: the exporter writes a fixed width and height,
    // which would overflow a narrow screen.
    svg: drawn.replace(/^<svg /, '<svg class="diagram" preserveAspectRatio="xMidYMid meet" '),
  };
}

const page = ({ slug, title, description, body }) => `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${escape(title)}</title>
    <meta name="description" content="${escape(description)}" />
    <link rel="canonical" href="${SITE}${slug}" />
    <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
    <meta property="og:title" content="${escape(title)}" />
    <meta property="og:description" content="${escape(description)}" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="${SITE}${slug}" />
    <style>${CSS}</style>
  </head>
  <body>
    <header>
      <a class="wordmark" href="/">draft</a>
      <nav>
        <a href="/dialects/">Dialects</a>
        <a href="/privacy/">Privacy</a>
        <a href="https://github.com/linzeyan/draft">Source</a>
        <a class="cta" href="/app/">Open the app</a>
      </nav>
    </header>
    <main>${body}</main>
    <footer>
      <p>
        draft is free software under the MIT licence. It runs in your browser,
        on your desktop, and on the command line. No account, no server, no
        telemetry.
      </p>
      <p><a href="https://github.com/linzeyan/draft">Source and issues</a> · <a href="/privacy/">What happens to your schema</a></p>
    </footer>
  </body>
</html>
`;

const CSS = `
  :root { color-scheme: light dark; --ink:#15181d; --dim:#5b6675; --line:#dfe3e9;
          --bg:#ffffff; --panel:#f6f7f9; --link:#1e5fd0; }
  @media (prefers-color-scheme: dark) {
    :root { --ink:#e6e9ef; --dim:#97a1b0; --line:#2a303a; --bg:#15181d;
            --panel:#1b1f26; --link:#79aaff; }
  }
  * { box-sizing: border-box; }
  body { margin:0; background:var(--bg); color:var(--ink);
         font:400 16px/1.6 ui-sans-serif, system-ui, -apple-system, sans-serif; }
  header, main, footer { max-width: 56rem; margin:0 auto; padding:0 1.25rem; }
  header { display:flex; align-items:center; gap:1rem; flex-wrap:wrap;
           padding-top:1.25rem; padding-bottom:1.25rem; }
  .wordmark { font-weight:600; font-size:1.15rem; letter-spacing:-0.01em;
              text-decoration:none; color:var(--ink); }
  nav { margin-left:auto; display:flex; gap:1rem; align-items:center; flex-wrap:wrap; }
  a { color:var(--link); }
  nav a { text-decoration:none; color:var(--dim); font-size:0.94rem; }
  nav a:hover { color:var(--ink); }
  .cta { background:var(--link); color:#fff !important; padding:0.4rem 0.9rem;
         border-radius:6px; font-weight:500; }
  h1 { font-size:2.1rem; line-height:1.2; letter-spacing:-0.02em; margin:1.5rem 0 0.75rem; }
  h2 { font-size:1.3rem; margin:2.5rem 0 0.75rem; letter-spacing:-0.01em; }
  h3 { font-size:1.05rem; margin:1.75rem 0 0.5rem; }
  .lead { font-size:1.15rem; color:var(--dim); max-width:42rem; }
  pre { background:var(--panel); border:1px solid var(--line); border-radius:8px;
        padding:0.9rem 1rem; overflow-x:auto; font-size:0.86rem; line-height:1.5;
        font-family: ui-monospace, SFMono-Regular, Menlo, monospace; }
  code { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size:0.9em; }
  figure { margin:1.5rem 0; }
  figure svg.diagram, figure img { display:block; width:100%; height:auto;
        background:#fff; border:1px solid var(--line); border-radius:8px; }
  figcaption { color:var(--dim); font-size:0.88rem; margin-top:0.5rem; }
  ul { padding-left:1.2rem; }
  li { margin:0.35rem 0; }
  .facts { display:flex; gap:1.5rem; flex-wrap:wrap; list-style:none; padding:0;
           margin:1rem 0; color:var(--dim); font-size:0.94rem; }
  .facts strong { color:var(--ink); font-size:1.25rem; display:block;
                  font-variant-numeric:tabular-nums; }
  .cards { display:grid; gap:1rem; grid-template-columns:repeat(auto-fit,minmax(14rem,1fr));
           padding:0; list-style:none; margin:1.25rem 0; }
  .cards a { display:block; padding:1rem; border:1px solid var(--line);
             border-radius:8px; text-decoration:none; color:var(--ink); }
  .cards a:hover { border-color:var(--link); }
  .cards span { display:block; color:var(--dim); font-size:0.9rem; margin-top:0.25rem; }
  footer { border-top:1px solid var(--line); margin-top:4rem; padding-top:1.5rem;
           padding-bottom:3rem; color:var(--dim); font-size:0.9rem; }
  footer p { max-width:42rem; }
`;

// Each entry is a dialect page. The notes describe what is actually in the
// fixture beside it — they are checked against it by eye once, and the numbers
// and the diagram below them are regenerated on every build.
const DIALECTS = [
  {
    slug: "postgres",
    card: "pg_dump output, ALTER TABLE keys",
    name: "PostgreSQL",
    fixture: "fixtures/dialects/postgres.sql",
    title: "PostgreSQL schema diagrams from pg_dump output",
    blurb:
      "Point draft at a pg_dump file and read it as a diagram. Schema-qualified names, keys declared through ALTER TABLE, quoted reserved words and multi-word types all parse.",
    notes: [
      "<code>public.users</code>-style schema qualification, kept out of the displayed name",
      "keys added after the fact by <code>ALTER TABLE … ADD CONSTRAINT</code>, including <code>ON DELETE CASCADE</code>",
      "reserved words quoted by pg_dump, such as <code>public.\"order\"</code>",
      "multi-word types — <code>character varying(255)</code>, <code>timestamp without time zone</code>",
      "arrays (<code>text[]</code>) and <code>jsonb</code> defaults containing braces and casts",
      "<code>SET</code>, <code>OWNER TO</code>, <code>CREATE INDEX</code> and <code>CREATE VIEW</code>, all skipped without complaint",
    ],
  },
  {
    slug: "mysql",
    card: "mysqldump, backticks, inline keys",
    name: "MySQL",
    fixture: "fixtures/dialects/mysql.sql",
    title: "MySQL schema diagrams from mysqldump output",
    blurb:
      "Drop in a mysqldump file. Backticked identifiers, version-gated comments, inline keys and foreign keys to tables the file never defines are all handled.",
    notes: [
      "backticked identifiers everywhere, including inside <code>REFERENCES</code>",
      "version-gated <code>/*!40101 … */</code> comments, which are executable SQL to MySQL and noise here",
      "inline <code>PRIMARY KEY</code>, <code>UNIQUE KEY</code>, <code>KEY</code> and <code>FULLTEXT KEY</code> clauses",
      "named <code>CONSTRAINT … FOREIGN KEY</code> with <code>ON DELETE</code> and <code>ON UPDATE</code> actions",
      "column <code>COMMENT</code> text containing semicolons, double dashes and brackets, none of which split the statement",
      "a foreign key pointing at <code>store</code>, a table this dump does not contain — drawn as a stub rather than dropped",
    ],
  },
  {
    slug: "sqlite",
    card: ".schema output, typeless columns",
    name: "SQLite",
    fixture: "fixtures/dialects/sqlite.sql",
    title: "SQLite schema diagrams from a .schema dump",
    blurb:
      "Paste the output of <code>.schema</code>. Inline REFERENCES, IF NOT EXISTS and SQLite's typeless columns all parse.",
    notes: [
      "<code>CREATE TABLE IF NOT EXISTS</code> with double-quoted identifiers",
      "column-level <code>REFERENCES \"notebook\"(\"id\")</code> with a delete action",
      "<code>AUTOINCREMENT</code>, and defaults that are function calls with quoted arguments",
      "the typeless column form — <code>CREATE TABLE tagless (a, b, c)</code> — which is legal in SQLite and nowhere else",
    ],
  },
  {
    slug: "sql-server",
    card: "bracketed names, clustered keys",
    name: "SQL Server",
    fixture: "fixtures/dialects/sqlserver.sql",
    title: "SQL Server schema diagrams from a scripted database",
    blurb:
      "Bracketed identifiers, bracketed type names and clustered primary keys with a sort direction, read the way SSMS scripts them.",
    notes: [
      "<code>[dbo].[Customer]</code> bracket quoting, on tables, columns and types alike",
      "<code>[int] IDENTITY(1,1)</code> and parameterised <code>[numeric](10, 2)</code>",
      "<code>CONSTRAINT … PRIMARY KEY CLUSTERED ([CustomerId] ASC)</code>, sort direction and all",
      "foreign keys added by a separate <code>ALTER TABLE … ADD CONSTRAINT</code> statement",
    ],
  },
  {
    slug: "snowflake",
    card: "three-part names, transient tables",
    name: "Snowflake",
    fixture: "fixtures/dialects/snowflake.sql",
    title: "Snowflake schema diagrams from a DDL export",
    blurb:
      "Three-part names, transient tables and constraints named before their kind — the shapes a Snowflake DDL export actually has.",
    notes: [
      "<code>create or replace transient table</code>, and <code>create table if not exists</code>",
      "three-part names such as <code>ANALYTICS.PUBLIC.ACCOUNT</code>",
      "constraints written name-first: <code>constraint PK_EVENT_LOG primary key (EVENT_ID)</code>",
      "Snowflake types including <code>variant</code> and <code>timestamp_ntz(9)</code>",
      "all-lowercase keywords, which the parser treats no differently from shouting",
    ],
  },
];

await rm(DIST, { recursive: true, force: true });
await mkdir(DIST, { recursive: true });

const written = [];
async function emit(slug, html) {
  const dir = slug === "/" ? DIST : resolve(DIST, slug.replace(/^\/|\/$/g, ""));
  await mkdir(dir, { recursive: true });
  await writeFile(resolve(dir, "index.html"), html);
  written.push(slug);
}

// ---------------------------------------------------------------- home

const hero = run("crates/app/src/sample.sql");

await emit(
  "/",
  page({
    slug: "/",
    title: "draft — read a SQL schema as an ER diagram",
    description:
      "Paste a CREATE TABLE script and get an ER diagram you can pan, zoom and edit. Runs entirely in your browser. Nothing is uploaded. Free and open source.",
    body: `
      <h1>Read a SQL schema as a diagram</h1>
      <p class="lead">
        Paste a <code>CREATE TABLE</code> script — a migration, a
        <code>pg_dump</code>, a file from a codebase you did not write — and get
        an entity-relationship diagram you can pan, zoom and edit. It runs
        entirely in your browser. Nothing is uploaded.
      </p>
      <p><a class="cta" href="/app/">Open the app</a></p>

      <figure>
        ${hero.svg}
        <figcaption>
          ${plural(hero.tables.length, "table")} and
          ${plural(hero.relations.length, "relation")}, laid out automatically.
          This picture was produced by the command line tool on this page's
          build, from the same code the app runs.
        </figcaption>
      </figure>

      <h2>The SQL is the document</h2>
      <p>
        Most diagram tools import your schema into a model of their own, and from
        then on you have two copies that drift. draft keeps one. The diagram is
        a projection of the text, and editing the diagram rewrites the exact bytes
        of your script.
      </p>
      <p>
        Rename a table on the canvas and every <code>REFERENCES</code> and key
        clause that mentions it is updated in place. Your comments, your blank
        lines, your vendor-specific clauses the parser never even understood —
        all still there, byte for byte, because nothing outside the span being
        changed is ever touched.
      </p>

      <h2>What it does</h2>
      <ul>
        <li>Automatic layout, tuned so a wide schema folds into something a screen can hold instead of a ribbon.</li>
        <li>Pan, zoom and level of detail; hover a table to fade everything it is not connected to.</li>
        <li>Drag tables where you want them; they stay put.</li>
        <li>A syntax-highlighted SQL pane beside the diagram, which redraws as you type.</li>
        <li>Two-way editing: double-click a table name, column name or type and change it.</li>
        <li>Sticky notes and group boxes, for the things the schema does not say.</li>
        <li>Save a project as one JSON file, or copy a link that carries the whole thing.</li>
        <li>Open a schema straight from a URL: paste a raw <code>.sql</code> link, or put it in one.</li>
        <li>Export SVG, PNG or WebP for a document or a pull request.</li>
      </ul>

      <h2>Nothing is uploaded</h2>
      <p>
        There is no server to upload to. The parser, the layout engine and the
        renderer are compiled to WebAssembly and run in your tab. Even a share
        link is not hosted: the project is compressed into the URL fragment, and
        browsers never transmit a fragment. A test in this repository drives the
        real application in a real browser and fails if anything leaves the
        origin that you did not ask for — the one thing you can ask for is a
        <code>#u=</code> link to a schema on another server.
        <a href="/privacy/">The details are here.</a>
      </p>

      <h2>Your dialect</h2>
      <ul class="cards">
        ${DIALECTS.map((d) => `<li><a href="/${d.slug}/">${d.name}<span>${d.card}</span></a></li>`).join("\n        ")}
      </ul>

      <h2>Also a command line tool</h2>
      <p>
        The same parser, layout engine and renderer build as a native binary with
        no window at all — useful in a build, a pre-commit hook, or a pull
        request comment.
      </p>
<pre><code>$ draft render schema.sql -o schema.svg
$ draft render schema.sql --png -o schema.png
$ draft render schema.sql --json | jq '.relations | length'</code></pre>
      <p>And as a desktop application for macOS, Linux and Windows.</p>
    `,
  }),
);

// ---------------------------------------------------- dialect index + pages

await emit(
  "/dialects/",
  page({
    slug: "/dialects/",
    title: "SQL dialects draft reads",
    description:
      "Worked examples of draft parsing PostgreSQL, MySQL, SQLite, SQL Server and Snowflake DDL, generated from the project's own test fixtures.",
    body: `
      <h1>SQL dialects draft reads</h1>
      <p class="lead">
        There is one parser, and it is deliberately tolerant rather than
        dialect-specific: it recognises the shapes <code>CREATE TABLE</code>
        takes in practice and steps over everything else without complaining.
        Each page below is generated by running the shipped tool over the
        fixture shown on it.
      </p>
      <ul class="cards">
        ${DIALECTS.map((d) => `<li><a href="/${d.slug}/">${d.name}<span>${d.card}</span></a></li>`).join("\n        ")}
      </ul>
      <h2>Anything else</h2>
      <p>
        A dialect with no page here is not a dialect that fails. The parser reads
        <code>CREATE TABLE</code>, column definitions, inline and table-level key
        constraints, and <code>ALTER TABLE … ADD CONSTRAINT</code>; it skips
        statements it does not recognise rather than refusing the file. If yours
        does not come out right,
        <a href="https://github.com/linzeyan/draft">open an issue with the DDL</a>.
      </p>
    `,
  }),
);

for (const dialect of DIALECTS) {
  const parsed = run(dialect.fixture);
  const sql = await readFile(resolve(ROOT, dialect.fixture), "utf8");
  await emit(
    `/${dialect.slug}/`,
    page({
      slug: `/${dialect.slug}/`,
      title: `${dialect.title} — draft`,
      description: `${dialect.blurb.replace(/<[^>]+>/g, "")} Free, open source, and runs entirely in your browser.`,
      body: `
      <h1>${escape(dialect.title)}</h1>
      <p class="lead">${dialect.blurb}</p>
      <p><a class="cta" href="/app/">Open the app</a></p>

      <h2>What the parser makes of it</h2>
      <ul class="facts">
        <li><strong>${parsed.tables.length}</strong> ${parsed.tables.length === 1 ? "table" : "tables"}</li>
        <li><strong>${parsed.columns}</strong> ${parsed.columns === 1 ? "column" : "columns"}</li>
        <li><strong>${parsed.relations.length}</strong> ${parsed.relations.length === 1 ? "relation" : "relations"}</li>
      </ul>
      <ul>
        ${dialect.notes.map((n) => `<li>${n}</li>`).join("\n        ")}
      </ul>

      <h2>The diagram</h2>
      <figure>
        ${parsed.svg}
        <figcaption>Drawn from the file below by <code>draft render</code>, on this page's build.</figcaption>
      </figure>

      <h2>The file</h2>
      <p>
        This is the project's ${escape(dialect.name)} test fixture, in full and
        unedited. Everything above was produced from it.
      </p>
<pre><code>${escape(sql.trimEnd())}</code></pre>
    `,
    }),
  );
}

// ------------------------------------------------------------- privacy

await emit(
  "/privacy/",
  page({
    slug: "/privacy/",
    title: "What happens to your schema — draft",
    description:
      "draft has no backend. Your schema is parsed and drawn in your own browser, share links live in the URL fragment, and the only request that ever leaves the origin is one you asked for by name.",
    body: `
      <h1>What happens to your schema</h1>
      <p class="lead">
        Nothing leaves your machine unless you ask for it, and there is exactly
        one way to ask. This page says what that means, because "we take your
        privacy seriously" is not a technical claim and cannot be checked.
      </p>

      <h2>There is no backend</h2>
      <p>
        draft is a static file. The parser, the layout engine, the renderer and
        the exporters are compiled to WebAssembly and execute in your tab. There
        is no API to call, no account to create, and no analytics script. Once
        the page has loaded you can disconnect from the network and everything
        still works.
      </p>

      <h2>Share links are not hosted</h2>
      <p>
        "Copy link" compresses your project — the SQL, the layout, your notes —
        and puts it in the URL <em>fragment</em>, the part after the
        <code>#</code>. Browsers never send the fragment to a server; it exists
        only in the address bar and in whatever you paste it into. That is why
        the link needs no storage behind it, and why a link you never share is
        never anywhere.
      </p>
      <p>
        The corollary is worth stating plainly: a link you <em>do</em> share
        carries the whole schema to whoever opens it. Treat it as you would the
        file.
      </p>

      <h2>What is stored locally</h2>
      <p>
        The app keeps your current document in your browser's local storage so
        that reloading the tab does not lose your work. It stays on your device,
        it is readable only by this origin, and clearing site data removes it.
        Saving a project or exporting an image writes a file to your computer
        through the ordinary download mechanism.
      </p>

      <h2>The one request that does go out</h2>
      <p>
        A link of the form <code>#u=https://…/schema.sql</code> asks draft to
        fetch that file and draw it. That is a request to somebody else's server,
        and it happens only when the link says so — never on an ordinary visit,
        and never for a schema you typed, pasted or opened. The URL sits in the
        fragment like everything else here, so it is not sent to whoever hosts
        draft either. Nothing of yours travels with the request: it is a plain
        <code>GET</code> for the file the link names.
      </p>

      <h2>How this is verified</h2>
      <p>
        The claim is tested rather than asserted. A script in the repository
        drives the real application in a real browser, records every network
        request every tab makes from launch to exit, and fails the build if
        anything leaves the origin that was not asked for, if any request carries
        the project payload, or if anything uses a method other than
        <code>GET</code>. With a <code>#u=</code> link it asserts the opposite
        too: exactly one outbound request, for exactly the file named.
      </p>

      <h2>The landing pages</h2>
      <p>
        The pages around this one are plain HTML with no script, no fonts and no
        images loaded from anywhere else. There is nothing here to set a cookie.
      </p>
    `,
  }),
);

// ------------------------------------------------------- assets and app

await cp(resolve(HERE, "favicon.svg"), resolve(DIST, "favicon.svg"));
await writeFile(
  resolve(DIST, "robots.txt"),
  `User-agent: *\nAllow: /\n\nSitemap: ${SITE}/sitemap.xml\n`,
);
await writeFile(
  resolve(DIST, "sitemap.xml"),
  `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${written.map((slug) => `  <url><loc>${SITE}${slug}</loc></url>`).join("\n")}
</urlset>
`,
);

let app = "not built — run `make web-build` to include it";
try {
  await cp(APP, resolve(DIST, "app"), { recursive: true });
  app = "included at /app/";
} catch {
  /* The pages are still valid without it; the deploy target is what needs both. */
}

console.log(`  ${written.length} pages into web/dist`);
for (const slug of written) console.log(`    ${slug}`);
console.log(`  robots.txt, sitemap.xml (${SITE})`);
console.log(`  application: ${app}`);
